FROM node:18 as bootstrap

WORKDIR /usr/src/app
RUN yarn init -yp && \
    yarn add "@angular/cli@17" && \
    yarn ng new {{cookiecutter.npm_slug}} \
        --prefix={{cookiecutter.app_prefix}} \
        --ssr \
        --skip-git=true \
        --skip-install=true \
        --package-manager=yarn \
        --style=scss \
        --routing=true

COPY . /usr/src/app/{{cookiecutter.npm_slug}}/
WORKDIR /usr/src/app/{{cookiecutter.npm_slug}}
RUN rm src/favicon.ico .editorconfig && \
    yarn && \
    yarn ng add @angular/localize --skip-confirmation && \
    yarn ng extract-i18n --output-path locale

VOLUME /usr/src/app/frontend
CMD cp -r * .* ../frontend/
