language: python
python:
  - 3.6
  - 3.7
services:
  - postgresql
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.yarn-cache
    - node_modules
before_install:
  - nvm install 10
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - pip install virtualenv
  - pip install cookiecutter
  - pip install pip-tools
  - yarn global add @angular/cli chromedriver geckodriver webdriver
script:
  - cookiecutter . --no-input
  - cd dighum_pro
  - cat bootstrap.log  
  - yarn
  - yarn django migrate
  - yarn start-p &
  - yarn test
