language: python
python:
  - 3.6
services:
  - postgresql
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.yarn-cache
    - node_modules
before_install:
  - nvm install 10
  - google-chrome-stable --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - pip install virtualenv
  - pip install cookiecutter
  - pip install pip-tools
  - yarn global add chromedriver geckodriver webdriver
script:
  - cookiecutter . --no-input
  - cd dighum_pro
  - cat bootstrap.log
  - yarn
  - yarn django migrate
  - yarn static-p
  - find static
  - yarn start-back-p &
  - yarn test
