language: python
python:
  - 3.6
services:
  - postgresql
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.yarn-cache
    - node_modules
before_install:
  - nvm install 10
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - pip install cookiecutter
  - pip install pip-tools
  - yarn global add @angular/cli
script:
  - cookiecutter . --no-input
  - cd dighum_pro
  - cat bootstrap.log
  - cd backend && pip-compile && cd ..
  - cd functional-tests && pip-compile && cd ..
  - yarn
  - yarn django migrate
  - yarn serve-p & yarn test
