language: python
python:
  - 3.6
services:
  - postgresql
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.yarn-cache
    - node_modules
before_install:
  - sudo apt-get install git-flow
  # Needed to run headless chrome
  - sudo apt-get install xorg xvfb gtk2-engines-pixbuf dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
  - sudo Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99
  - nvm install 10
  - google-chrome-stable --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - pip install virtualenv
  - pip install cookiecutter
  - pip install pip-tools
  - yarn global add geckodriver webdriver
before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`  
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
script:
  - cookiecutter . --no-input
  - cd dighum_pro
  - cat bootstrap.log
  - yarn
  - yarn django migrate
  - yarn static-p
  - find static
  - yarn start-back-p &
  - chromedriver --version
  - yarn test -o webdriver=Firefox
