language: python
python:
  - 3.4
  - 3.5
  - 3.6
services:
  - postgresql
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.yarn-cache
    - frontend/node_modules
before_install:
  - nvm install 10
  - google-chrome-stable --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - yarn global add geckodriver webdriver
before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
script:
  - yarn
  - yarn django migrate
  - yarn static-p
  - find static
  - yarn start-back-p &
  - chromedriver --version
  - yarn test
