language: python
python:
  - 3.4
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - yarn global add chromedriver geckodriver webdriver
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  directories:
    - frontend/node_modules
script:
  - source .env/bin/activate
  - yarn
  - yarn django migrate
  - yarn serve-p & yarn test
