language: python
python:
  - 3.4
services:
  - postgresql
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.yarn-cache
    - frontend/node_modules
addons:
  chrome: stable
before_install:
  - nvm install 10
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - yarn global add chromedriver geckodriver webdriver
script:
  - source .env/bin/activate
  - yarn
  - yarn django migrate
  - yarn test-back && yarn test-front
