version: '3.8'

services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/static
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
  db:
    image: postgres
    environment:
      - POSTGRES_DB={{cookiecutter.database_name}}
      - POSTGRES_USER={{cookiecutter.database_user}}
      - POSTGRES_PASSWORD={{cookiecutter.database_password}}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build:
      context: ./backend
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - static_data:/app/staticfiles
    depends_on: 
      - db
    env_file:
      - ./.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
    command: ng serve --host 0.0.0.0

volumes:
  postgres_data:
  static_data: 