services:
  db:
    image: docker.io/postgres:16
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - PGHOST=${SQL_HOST}
      - PGPORT=${SQL_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data/
  backend:
    build:
      context: ./backend
    volumes:
      - type: bind
        source: ./backend
        target: /backend
      - type: bind
        source: ./frontend/build
        target: /frontend/build
      - static_data:/backend/staticfiles
    environment:
      - PGDATABASE=${SQL_DATABASE}
      - PGUSER=${SQL_USER}
      - PGPASSWORD=${SQL_PASSWORD}
      - PGHOST=${SQL_HOST}
      - PGPORT=${SQL_PORT}
    depends_on:
      - db
    env_file:
      - ./.env.dev
    ports:
      - "127.0.0.1:8000:8000"
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
{% if cookiecutter.frontend == 'angular' %}
  frontend:
    build:
      context: ./frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    ports:
      - 127.0.0.1:4200:4200
    command: yarn start
{% endif %}
{% if cookiecutter.saml_authentication == "Yes, please!" %}
  test-idp:
    image: ghcr.io/centrefordigitalhumanities/development-idp/development-idp:develop
    ports:
      - "127.0.0.1:7000:7000"
{% endif %}

volumes:
  db_data:
  static_data:
