version: '3'

services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
  db:
    image: postgres
    environment:
      - POSTGRES_DB=chocchip
      - POSTGRES_USER=chocchip
      - POSTGRES_PASSWORD=chocchip
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build:
      context: ./backend
    depends_on: 
      - db
    env_file:
      - ./.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend

volumes:
  postgres_data: